# Generated by Django 4.1.13 on 2024-10-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('recipe_id', models.CharField(max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipe_id', models.CharField(max_length=20)),
                ('minutes', models.IntegerField(default=0)),
                ('n_steps', models.IntegerField(default=0)),
                ('steps', models.TextField()),
                ('ingredients', models.TextField()),
                ('n_ingredients', models.IntegerField()),
                ('calories', models.DecimalField(decimal_places=1, max_digits=7)),
                ('total_fat', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('sodium', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('saturated_fat', models.IntegerField()),
                ('carbohydrates', models.IntegerField()),
                ('recipe_count', models.IntegerField()),
                ('mean_rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
