# Generated by Django 4.1.13 on 2024-10-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactioninfo',
            name='user_id',
            field=models.CharField(max_length=20),
        ),
    ]
