# Generated by Django 4.1.13 on 2024-10-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_alter_interactioninfo_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.CharField(max_length=20)),
            ],
        ),
    ]
