# Generated by Django 4.1.13 on 2024-10-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_recipestorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestorage',
            name='model_id',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
