# Generated by Django 4.1.13 on 2024-10-04 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_recipestorage_model_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipestorage',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='recipestorage',
            name='recipe_ids',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
